---
# sample playbook for site-modules
- hosts: all
  tasks:
    - name: install glibc
      pacman:
        name: glibc
        state: latest
      become: yes
    - name: install aur packages with makepkg
      makepkg:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - jansson
        - jshon
        - packer
      tags:
        - makepkg

    - name: install aur packages with packer
      packer:
        name: downgrade
        state: present
      become: yes
      tags:
        - packer
